### ISSUE TITLE
在win10上无法使用

### ISSUE THREAD

**Issue by iAoe444** [march1993/win-sw-vd#1]
命令行输入win-sw-vd.exe left和win-sw-vd.exe right都没反应，已经创建了两个虚拟桌面了

**Comment by iAoe444** [comment]
可以了，这个在mstc才有用

**Comment by march1993** [comment]
> 命令行输入win-sw-vd.exe left和win-sw-vd.exe right都没反应，已经创建了两个虚拟桌面了

直接双击运行也没有反应吗？

**Comment by iAoe444** [comment]
我在本机上面创建两个虚拟桌面，然后直接双击，或者使用命令行都没有反应。然后我发现只有处在远程桌面全屏下，鼠标绑定win-sw-vd.exe right这个命令，才可以切换了，切换回本机桌面，我鼠标另外一个按键绑定win+ctrl+right，又可以切换回去，目前的方案是这样

**Comment by march1993** [comment]
> 我在本机上面创建两个虚拟桌面，然后直接双击，或者使用命令行都没有反应。然后我发现只有处在远程桌面全屏下，鼠标绑定win-sw-vd.exe right这个命令，才可以切换了，切换回本机桌面，我鼠标另外一个按键绑定win+ctrl+right，又可以切换回去，目前的方案是这样

更新了个 v1.1，支持win10了，快试一下吧

**Comment by iAoe444** [comment]
可以了，超好用
